добавил разметку главной страницы
htmlacademy-htmlcss/1690249-sedona-30 pull request #2
Opened 2021-01-24 05:58 UTC by ikonnikoweb

2021-01-24 12:52 UTC, Zakamsky requested changes
Очень хорошее исполнение, есть небольшие ошибки, но они есть у всех.
На второй странице есть рад ошибок дублирующих первую я не стал их отмечать посмотри сам пожалуйста.
Огромный респект за комментарии и порядок в коде.

2021-01-24 12:52 UTC, Zakamsky commented on index.html
> +        </section>
Все хорошо, но секция должна иметь свой заголовок, поэтому надо решить добавить скрытый заголовок, или заменить секцию на что то еще.

2021-01-24 12:52 UTC, Zakamsky commented on index.html
> +
Отсюда и далее мы имеем прямо пронумерованный список причин, а внутри него , вложенный ненумерованный... список. Может какой то семантический тэг для этого?

2021-01-24 12:52 UTC, Zakamsky commented on index.html
> +              <img src="img/icon-1.svg" alt="home" width="75" height="72">
Здесь и далее, одноцветные иконки не несут никакой смысловой нагрузки кроме некоторого декоративного оформления, думаю лучше будет оставить их для фоновых изображений.

2021-01-24 12:52 UTC, Zakamsky commented on index.html
> +              <button type="button"><img src="img/calendar.svg" alt="calendar"></button>
Форма очень хороша, но я бы предложил явно указать тип кнопки, а еще ты уверен в необходимости кнопок с календариком?
Но даже если да - иконка внутри кнопки точно не является контентным изображением.

2021-01-24 12:52 UTC, Zakamsky commented on index.html
> +          <form action="https://echo.htmlacademy.ru" method="get">
ой, чуть не пропустил еще одну секцию без заголовка.

2021-01-24 12:52 UTC, Zakamsky commented on index.html
> +          </ul>
Опять же иконки в разметке...  Можно позволить себе разместить иконки в разметку только в том случае если это сложный свг которому нужны состояния по наведению которые мы не можем получить используя внешний файл, в ов сех сотальных случаях мы должны разделять сожержане (контент) от оформления.

2021-01-24 12:52 UTC, Zakamsky commented on catalog.html
> +                <form action="https://echo.htmlacademy.ru" method="post">
Такая же ошибка как на главной

2021-01-24 12:52 UTC, Zakamsky commented on catalog.html
> +                </form>
В целом форма отлично выполнена, на 4+
не хватает только сабмита с текстом показать, и в последний филдсет, советую сразу положить два поля для чисел минимум и максимум, которые будут скрыты но они нужны.

2021-01-24 12:52 UTC, Zakamsky commented on catalog.html
> +                    <a href="#"><img src="img/icon-down.svg" alt="down"></a>
опять иконки в контенте....

2021-01-24 15:42 UTC, ikonnikoweb commented on index.html
> +              <button type="button"><img src="img/calendar.svg" alt="calendar"></button>
3.12. Иконка календаря в поле ввода даты должна быть добавлена отдельным элементом, чтобы в будущем на неё программист мог повесить событие нажатия для открытия календаря с возможностью выбора даты. ( это из ТЗ )
 я так понял что можно будет эти иконки календаря разметить как псевдоэлементы с фоновым изображением? и потом на них уже повесить событие при нажатии? или лучше сделать их как `<span>` ?

2021-01-24 17:01 UTC, ikonnikoweb commented on index.html
> +        </section>
заменил на `<div>`

2021-01-24 17:03 UTC, ikonnikoweb commented on index.html
> +
+

2021-01-24 17:06 UTC, ikonnikoweb commented on index.html
> +          <form action="https://echo.htmlacademy.ru" method="get">
насчет заголовков понял, когда прогонял через валидатор, но думал не критично. Так понимаю их важно использовать для SEO?  Или не только?

2021-01-24 17:08 UTC, ikonnikoweb commented on index.html
> +          </ul>
Спасибо за подробный комментарий, надеюсь я понял смысл.

2021-01-24 17:12 UTC, ikonnikoweb commented on catalog.html
> +                </form>
поля добавил, насчет шкалы пока не понимаю, разметить её просто как какой то `div` а потом добавить  два псевдо элемента (два ползунка) ? или пока рано его трогать и можно оставить как есть?

2021-01-25 00:06 UTC, Zakamsky commented on index.html
> +          <form action="https://echo.htmlacademy.ru" method="get">
Это не только или даже не столько для СЕО, т.к. сео роботы научились игнорировать скрытые элементы (раньше делали чуть ли не отдельный скрытый сайт для роботов и нормальный сайт для людей), т.е. заголовки мы пишем для людей работающих со вспомогательными технологиями и логической разбивки контента для разных краулеров и парсеров. НО сейчас все вращается вокруг доступности, поэтому она влияет на сЕО опосредованно и разбитый на логические озаглавленные группы контент лучше индексируется, т.е. опять влияет на СЕО. Хотя прямых метрик что бы это измерить нет, и стараемся мы все же для людей.

2021-01-25 00:09 UTC, Zakamsky commented on index.html
> +              <button type="button"><img src="img/calendar.svg" alt="calendar"></button>
О, ты действительно прав был на счет кнопок, я не могу помнить весь тз всех проектов на изусть к сожалению, т.ч. кнопки потом вернем. почему не спаны? -для интерактивных элементов за крайне редким исключением нужно использовать интерактивные тэги, например кнопки или ссылки, если перехода нет - это кнопка. А вот псевдоэлемент не подойет 100% - на него нельзя повесить обработчик из js. а вот иконки вставить фонов в кнопку можно =).

2021-01-25 00:12 UTC, Zakamsky commented on catalog.html
> +                </form>
пока можно ничего не делать, тут надо знать как это делается. вам покажут. Но не псевдо - надо же из js как то обработать будет события.

2021-01-25 00:13 UTC, Zakamsky reviewed
Вот теперь все отлично, и форма на твердую 5.

2021-01-25 00:13 UTC, merged